pipeline {
  agent any

  tools {
     maven 'M399' 
  }

  stages {

    stage('Build') {
      steps {
        sh 'mvn clean package'
      }
      post {
        success {
          archiveArtifacts artifacts: '**/target/*.war'
        }
      }
    }

    
  }

}